### ISSUE TITLE
Switch to using Python

### ISSUE THREAD

**Issue by Themanwithoutaplan** [HTTPArchive/beta.httparchive.org#1]
Back in 2011 I ported httparchive to Python (using SQLAlchemy and Pyramid) and I think the port could be a good start for the planned reworking of the project.

The existing code is at https://bitbucket.org/charlie_x/python-httparchive/src/ 

Major differences to the original:

* separation of model and view code
* normalised and extended database for site reports (requests untouched), found queries ran much faster than with PHP/MySQL
* all charts use Google Visualisation (wrote gviz_data_table to do this)
* mobile and desktop reports are folded together
* switched to using Postgres because it does the heavy lifting better

In addition I have local code which I use for comparative reports for customers.

A currently poorly maintained version of the site can be seen at http://mamasnewbag.org I need to push the changes to the schema and update the imported data.

**Comment by rviscomi** [comment]
Thanks Charlie.

I see three main components to this: back end, data viz, and front end.

- Setting up on App Engine takes care of some of the things you mentioned. We'll be using Python and GAE comes with a few data storage options like Cloud SQL and Datastore. The starter docs included a Flask demo, so that's what I've checked in so far, but Pyramid is supported too. Open to changing if it means we can reuse a lot of what you've already written, or at least have a resident expert for writing new stuff with it.
- For the visualizations, [Highcharts](https://www.highcharts.com/demo) has more of the features we're looking for. But we definitely want to start folding mobile/desktop together. For example: http://jsfiddle.net/rviscomi/1r6dpctd/
- We're working with an agency to design and develop a new front end. This will be entirely from scratch, but still carry forward some of the familiar visual elements like colors and the logo. It will be delivered as static HTML/CSS so we'll have to make it fit into whatever templating system we want to use - I've started using Jinja. JS frameworks like React are also on the table.

So we won't be able to salvage a whole lot, but it definitely won't go to waste. The routing logic especially.
